# Generated by Django 3.2.11 on 2022-01-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('chemistry', models.FloatField(blank=True, null=True)),
                ('biology', models.FloatField(blank=True, null=True)),
                ('english', models.FloatField(blank=True, null=True)),
                ('roll_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.studentinfo')),
            ],
        ),
    ]
